---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kw-mvn
spec:
  selector:
    matchLabels:
      app: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: kb-mvn
          image: docker.vm01/kw-mvn:20221027-013838-6
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Seoul
