---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kw-mvn
spec:
  selector:
    matchLabels:
      stage: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: dev
    spec:
      containers:
        - name: kb-mvn
          image: docker.vm01/kw-mvn:dev-211105-145153-f7755115
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Seoul
---
apiVersion: v1
kind: Service
metadata:
  name: kw-mvn
  labels:
    stage: dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
      name: http-port
  type: NodePort
  selector:
    stage: dev
