apiVersion: v1
kind: Service
metadata:
  name: {{ include "kw-mvn.fullname" . }}
  labels:
    {{- include "kw-mvn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodeport }} 
      protocol: TCP
      name: http
  selector:
    {{- include "kw-mvn.selectorLabels" . | nindent 4 }}
